openapi: 3.0.0
info:
  title: Sample API for Dredd
  version: 0.0.1
servers:
  - url: http://localhost:3000
    description: Server localhost
paths:
  /v1/foo:
    get:
      summary: Returns greeting.
      description: Returns greeting description.
      responses:
        '200':    # status code
          description: A JSON containing greeting
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                items:
                  type: string
                example: {"message":"Hello World!"}
