swagger: '2.0'
info:
  version: '1.0'
  title: Example API
host: localhost
basePath: /v1
schemes:
  - http
paths:
  /foo:
    get:
      parameters:
        - in: header
          name: Authorization
          type: string
          default: Bearer tuwnVFNKyqgo
      produces:
        - application/json; charset=utf-8
      responses:
        '200':
          description: 'Sample GET request'
          schema:
            type: object
            properties:
              message:
                type: string
                example: foo
#              message1:       # disable this line for working CI
#                type: string  # disable this line for working CI
            required:
              - message
  /bar:
    get:
      parameters:
        - in: query
          name: id
          type: integer
        - in: header
          name: Authorization
          type: string
          default: Bearer tuwnVFNKyqgo
      produces:
        - application/json; charset=utf-8
      responses:
        '200':
          description: 'Endpoint with query param'
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 100500
