swagger: '2.0'
info:
  version: '1.0'
  title: Example API
host: localhost
basePath: /v1
schemes:
  - http
paths:
  /foo:
    get:
      produces:
        - application/json; charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              message:
                type: string
                example: foo
#              message1:       # disable this line for working CI
#                type: string  # disable this line for working CI
            required:
              - message
